//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

pub mod prelude;

pub mod tab_admin;
pub mod tab_software_info;
pub mod tab_software_category;
pub mod tab_software_category_relation;
pub mod tab_software_comment;
pub mod tab_software_version_info;
pub mod tab_organize_info;
pub mod tab_media_resource_info;
pub mod tab_member;
pub mod tab_admin_menu;
pub mod tab_provider_member;
pub mod tab_sys_region;
pub mod tab_organize_info_audit_history;
pub mod tab_software_info_audit_history;
pub mod tab_software_version_audit_history;

