//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

pub use super::tab_admin::Entity as TabAdmin;
pub use super::tab_software_info::Entity as TabSoftwareInfo;
pub use super::tab_software_category::Entity as TabAppCategory;
pub use super::tab_software_category_relation::Entity as TabAppCategoryRelation;
pub use super::tab_software_comment::Entity as TabSoftwareComment;
pub use super::tab_software_version_info::Entity as TabAppVersionInfo;
pub use super::tab_organize_info::Entity as TabOrganizeInfo;
pub use super::tab_media_resource_info::Entity as TabMediaResourceInfo;
pub use super::tab_member::Entity as TabMember;
pub use super::tab_provider_member::Entity as TabProviderMember;

