//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "tab_app_info")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub software_id: i64,
    pub app_name: String,
    pub app_logo: String,
    pub app_platform: i32,
    pub app_pack_name: String,
    pub company_id: i64,
    pub privacy_protocal_url: String,
    pub create_time: i64,
    pub delete_time: Option<i64>,
    pub update_time: Option<i64>,
    pub status: i32,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
